spring.application.name=eufood

spring.datasource.url=jdbc:mysql://localhost:3306/db_eufood
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update


sessao.usuario.tempo.expiracao.minutos=60

api.security.token.private.key=classpath:app.key
api.security.token.public.key=classpath:app.pub

spring.servlet.multipart.max-file-size=11MB
spring.servlet.multipart.max-request-size=11MB
caminho.disco.imagens=X:\\